name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  # Cancel previous actions from the same PR: https://stackoverflow.com/a/72408109
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  bazel-test:
    uses: bazel-contrib/.github/.github/workflows/bazel.yaml@v6
    with:
      folders: '[".", "example"]'
      # Only test with Bazel 6. And we don't try for Windows support yet.
      exclude: '[{"bazelversion": "5.4.0"}, {"os": "windows-latest"}]'

  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup bats
        uses: mig4/setup-bats@v1
        with:
          bats-version: "1.8.2"
      - name: Setup bats helpers
        uses: brokenpip3/setup-bats-libs@0.0.3
        with:
          support-path: /usr/lib/bats/bats-support
          support-version: "0.3.0"
          assert-path: /usr/lib/bats/bats-assert
          assert-version: "2.1.0"
      - name: "Integration test: example"
        working-directory: example
        run: bats ./test
      - name: "Integration test: format"
        working-directory: format
        run: bats ./test
